# -*- coding: utf-8 -*-
"""Spam classifier deployment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMTa5M0GcsT_ikcj9g515-4TTcbfGN2H
"""

!curl ipv4.icanhazip.com

!streamlit run app.py & npx localtunnel --port 8501